### ISSUE TITLE
Unknown database provider

### ISSUE THREAD

**Issue by MagnusIIIBR** [panthernet/ThunderED#1]
What am I doing wrong? Or did I stop doing something?

![image](https://user-images.githubusercontent.com/9530663/39675702-6c0b3fc4-5135-11e8-8143-33482e2d673e.png)

**Comment by panthernet** [comment]
Hi. in config **section** there should be an entry:

	"databaseProvider": "sqlite"

**Comment by MagnusIIIBR** [comment]
already.

![image](https://user-images.githubusercontent.com/9530663/39675878-969196ce-5137-11e8-86d9-b3166dcaabf6.png)

But the error continue....

**Comment by MagnusIIIBR** [comment]
Fixed:
I changed the settings.def.json to settings.json and worked.
