### ISSUE TITLE
Structure ownership transfer 

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#101]
Notification template is not publishing the original and the new corp name.
The notification.lg file has the correct info, however on discord only posts: "[...]has been transferred from  to !"

**Comment by panthernet** [comment]
I need message text from the notification_lg file. Please paste it between ``` ``` ``` symbols here to display it as a code

**Comment by srobi** [comment]
"OwnershipTransferred [1080326337]
charID: 2114282192
newOwnerCorpID: 755437926
oldOwnerCorpID: 98598067
solarSystemID: 30005307
structureID: 1031089311838
structureName: Aidart - Golden Cove
structureTypeID: 35825
"

**Comment by panthernet** [comment]
FYI when you post it like this
![image](https://user-images.githubusercontent.com/5926603/62608701-9b690380-b900-11e9-98db-193b18f524a6.png)

it will be posted in code wrap where all symbol data persist and not changed by web post  :)

**Comment by srobi** [comment]
```
OwnershipTransferred [1080326337]
charID: 2114282192
newOwnerCorpID: 755437926
oldOwnerCorpID: 98598067
solarSystemID: 30005307
structureID: 1031089311838
structureName: Aidart - Golden Cove
structureTypeID: 35825
```

one more attempt :P

**Comment by panthernet** [comment]
fixed
