### ISSUE TITLE
re-auth is not happening as configured time

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#102]
approx 220 users
"AuthCheckIntervalMinutes": 15
"AuthTakeNumberOfUsersPerPass": 300

last_check timestamp is older than 60 mins for every users.
every 2nd minute log entry: [    Info]: [CHK]: Fetched 0 users to check within this pass

It appears that the checking is done after 1 hour 15mins (approx.) my server time is EVE time +1 hour. Just guessing, maybe the bot is using server and Eve time in mixture causing this behaviour (15min set check + 1 hour server time difference).

**Comment by panthernet** [comment]
Yes, SQLite gets time in a special way. Fixed in V1.4.3
