### ISSUE TITLE
[Bug] Simplified Auth file not applying on start-up

### ISSUE THREAD

**Issue by Bluedagger21** [panthernet/ThunderED#103]
Sometime in the latest updates these past couple of weeks the simpified auth file feature has broke. Entries are no longer being recognized. The logs say processing has been successful and if I change an entity to be invalid, I get an error for that, too. But, valid entries are still not correctly being recognized. 

I am currently applying some simplified auth rules to our guest group (that has no requirements or preliminary auth) to further extend that authgroup.

**Comment by panthernet** [comment]
I've checked and it works for me. This is strange, because you will evetually get a warning in logs if entity, group or role hasn't been found. So I guess they're correct.

The obvious check I can recommend is the file name and location.

**Comment by panthernet** [comment]
Still having problems with this?
