### ISSUE TITLE
[Bug] Using filters when using web settings editor deleting other auth.

### ISSUE THREAD

**Issue by oskar94** [panthernet/ThunderED#105]
Today I was updating roles for a member using the web settings interface and used the search to filter down to only see their entry. When I then saved and reloaded the bot it started to remove roles from people that should have them. After stopping the bot I noticed that the _simplifiedAuth.txt file had shrunk in size and noticed that only the person that I had used search to limit to was saved in the file. Luckily I did have a backup from a few days ago to restore it.

**Comment by panthernet** [comment]
Fixed in 1.4.7
