### ISSUE TITLE
orbital reinforced is incorrectly parsed and multiplied

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#109]
Orbital reinforces:
1. "Reinforced mode will end, and the Customs Office will become vulnerable" date incorrectly published ( e.g. 152948d , 18h , 24m)

2. Three POCO reinforced consecutively , first was published by the bot once, 2nd twice and 3rd three times.
[Pocos.txt](https://github.com/panthernet/ThunderED/files/3706630/Pocos.txt)
[https://gyazo.com/f06d2c3feb6a6fc5ef359451dd7743e8](url)   - screenshot sample, the 3rd is repeated 3times

**Comment by panthernet** [comment]
It is good to have `notifications_lg.log` file content to check the event data. It is hard to reproduce POCO event  :)

**Comment by srobi** [comment]
[notifications_lg.log](https://github.com/panthernet/ThunderED/files/3788534/notifications_lg.log)
unfortunately I cannot interpret the date info.. so all orbital attack/reinforcement messages extracted from log  I do not know which one was the problematic..

Problem occurred on 04/10/2019

**Comment by panthernet** [comment]
Fixed in v1.4.4
