### ISSUE TITLE
contract notification issue

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#114]
contract notification re-publishes all contract (with outstanding status) when only one status (in progress) changed.

**Comment by panthernet** [comment]
Please elaborate on the issue. When exactly it happens, what contracts you have that is publishing and what is your config. You can send me the data in PM if you like.

**Comment by srobi** [comment]
Sending config in PM.
Setting: Bot reports courier contract (outstanding/deleted, in progress , completed/failed) to two discord channels (one with all details, other with short version).  Duplication happened at in progress and completed status for some contract (but if in-progress is duplicated then completed is duplicated too).
I cannot recognise clear logic - some contract are duplicated some not  - consistently both channels or neither (that the bot published at the same time on discord).
