### ISSUE TITLE
Discord Library Issues

### ISSUE THREAD

**Issue by D3m0nsam** [panthernet/ThunderED#117]
Bot is going offline at random times. https://pastebin.com/zuwNCmKu

Maybe look into a way to define the bot to restart every couple of hours in settings.json.

Maybe for Docker users have the bot exit our so if the flag --restart unless-stopped is set it just restart automatically.

**Comment by panthernet** [comment]
v1.4.9 has a solution for this. Also please check this page: https://github.com/panthernet/ThunderED/wiki/Troubleshooting
