### ISSUE TITLE
Mail failed to push if Message is too long

### ISSUE THREAD

**Issue by Beaconsilver** [panthernet/ThunderED#120]
`01/15/2020 04:44:28 [Critical]: Object reference not set to an instance of an object. 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ThunderED.Modules.MailModule.Run(Object prm) in /app/ThunderED/Modules/MailModule.cs:line 150`

Noticed that eve mails failed to get pushed if it's to long to fit in a single discord message

**Comment by panthernet** [comment]
Yes, there's something happening there but I can't track it. My test mails are running fine. If it is some special mail that failing to feed it would be nice to have it

**Comment by panthernet** [comment]
Should be fixed in v1.4.9
