### ISSUE TITLE
!Char Flipping Values

### ISSUE THREAD

**Issue by kiakri** [panthernet/ThunderED#122]
!char commands will have the value filled when you get Snuggly or Solo chance shown.

What it currently is
Snuggly = Dangerous Value
Solo = Gang Value

What is should be
Snuggly = Snuggly Value
Solo = Solo Value

**Comment by panthernet** [comment]
I need an example, All of mine works fine.

**Comment by kiakri** [comment]
Sorry i thought i added this myself. 

When someone hit's 75% it flips

This person has 74% dangerous but the bot pulls the Value as snuggly

![image](https://user-images.githubusercontent.com/7399660/77235115-138feb00-6bab-11ea-9682-0cd3af25ba4c.png)

![image](https://user-images.githubusercontent.com/7399660/77235120-25718e00-6bab-11ea-9451-7d67bd88348a.png)

**Comment by kiakri** [comment]
![image](https://user-images.githubusercontent.com/7399660/77235149-5e116780-6bab-11ea-8d3a-8fe4efe8018c.png)

![image](https://user-images.githubusercontent.com/7399660/77235155-636eb200-6bab-11ea-9938-52d18235e7ec.png)

**Comment by panthernet** [comment]
Should be fixed in v1.4.9
