### ISSUE TITLE
Add way to terminate bot while running as service.

### ISSUE THREAD

**Issue by oskar94** [panthernet/ThunderED#123]
Right now if you are using `RunAsServiceCompatibility` to get cpu usage down you are unable to softly shut down the bot. The only way to stop/restart the bot is to terminate the current session. This can corrupt the db file forcing either restoring to a old version if available or at worst full loss of auth data. 

My suggestion would be to add a discord command to stop the bot, and if possible still allow input from STDIN for attaching to a running docker container.

**Comment by panthernet** [comment]
Implemented in v1.4.9
