### ISSUE TITLE
Zkill rate limiting requests

### ISSUE THREAD

**Issue by mrurb** [panthernet/ThunderED#124]
I've noticed that for the stats module it gets rate limited.

![image](https://user-images.githubusercontent.com/3414748/80380847-68a4d800-88a0-11ea-8d2d-a7c2ac57b701.png)

**Comment by panthernet** [comment]
Merged pull request. Ideally I need to sort web requests by groups each with their own call frequency.

**Comment by mrurb** [comment]
I would suggest using the HttpClient with library named Polly. Polly will give you a much better workflow when it comes to calling external APIs and making good policies when things fail.

For this exact problem that we are running into here, there is a good read here: http://www.thepollyproject.org/2018/03/06/policy-recommendations-for-azure-cognitive-services/

**Comment by panthernet** [comment]
Yeah, i think i've seen it a couple of years ago. Had not much web related work since when :) thanks I'll take a look

**Comment by mrurb** [comment]
This is how I would implement it.
https://github.com/mrurb/ThunderED/tree/DevPolly
I've made some changes to how the program starts using dependency injection, as with Net Core and their IHttpClient factory and DI, you can get a really nice and robust HttpClient and coupling that with Polly, you get a strong httpclient that will error correct, a lot of error you might encounter otherwise.
