### ISSUE TITLE
.../merged/app /ThunderED/Data: not a directory

### ISSUE THREAD

**Issue by Morgathys** [panthernet/ThunderED#135]
I tried to install ThunderED twice (centos&ubuntu) on my GCP VM with this [documentation ](https://github.com/panthernet/ThunderED/wiki/Build-&-Installation) from the source code and both builds failed with the error msg:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process
caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/opt/thdwebserver" to rootfs at
"/app/ThunderED/Data" caused: mount through procfd: open o_path procfd: open
/var/lib/docker/overlay2/d94LOONGUUID2f9/merged/app/ThunderED/Data: not a directory: unknown:
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is
the expected type.
```

**Comment by Morgathys** [comment]
As workaround, I pulled the latest pre-compiled version and its worked.
_(method 2B from the install guide)_

**Comment by Morgathys** [comment]
Thanks @Demon on discord for the solution.

Instead starting the container with this command as mentioned in the documentation:
`docker run -d -p 8000:8000 -v /opt/thdwebserver:/app/ThunderED/Data thundered:latest`

use this one:
`docker run -d -p 8000:8000 -v /opt/thdwebserver:/app/Data thundered:latest`

**Comment by demon** [comment]
Wrong @demon :)
