### ISSUE TITLE
Same notifications gets repeated when switching notification source character

### ISSUE THREAD

**Issue by lunedis** [panthernet/ThunderED#14]
I use the notifications module for structure notifications and managing the corp members, so I get messages when people leave / join the corp.

For leaving corp messages one must use the CEO api access, so when we switched CEO i had to switch the characterid in the settings.json and reauth.

This caused all other notifications in the last 7 days to get posted to discord again (even though they were already there).

Is that intended behaviour?

**Comment by panthernet** [comment]
Probably intended as for every new feeder the bot will fetch notifications for a set period of time. I will look into making it optional.

**Comment by panthernet** [comment]
Added **fetchLastNotifDays** param to notification group. Default value is 0. So it will not fetch any old notifications for new feeder by default.
