### ISSUE TITLE
corporate logistic notifications - enhancement

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#16]
Create discord notifications when contracts are created, deleted, accepted, rejected, completed or failed.
- separate channel for "customer" (event: accepted, rejected, completed, failed) and for "logistic team" (event: created, deleted)
- selection if courier or item exchange or both
- selection of corporate or individual contract or both
- selectable/multiple  character ID to feed contracts (multiple logistic corp)

Message templates with contract basic data.

**Comment by panthernet** [comment]
Hi, I'll add it to my list but you can greatly help me if you gather these notifications info,
If you have **ModuleNotificationFeed** enabled then set **"LogNewNotifications": true**,

All notifications which are not supported yet will be logged into a separate log file. I can then implement them based on this data.

**Comment by srobi** [comment]
Hi, it is enabled but I think this is not coming as part of notification, the end points are:
GET /characters/{character_id}/contracts/ and GET /corporations/{corporation_id}/contracts/

**Comment by panthernet** [comment]
Okay I'm finally looking into it. It is difficult to inject this functionality into existing system as it require additional character permissions. Probably I can think about the standalone module, something like ContractWatcher with separate auth. It will monitor specified character/corporation contracts and post updates into designated channels. Quite a work though, will take some time.

**Comment by panthernet** [comment]
The first version is in the test process but will require some time to nail all the issues. Currently it don't use database and operate all the data in memory so it will require some time to enhance the logic. We'll see if I can release it in a couple of days.

**Comment by srobi** [comment]
thanks - happy to test if you have "beta" version; on discord Darwien D.

**Comment by panthernet** [comment]
Available on GitHub and testing.
