### ISSUE TITLE
HR Module Skill List

### ISSUE THREAD

**Issue by Bluedagger21** [panthernet/ThunderED#18]
Currently the HR Module only shows total SP. This issue is to request a new tab in the HR Module giving a breakdown of SP allocation per skill in a collapsible category list.

**Comment by panthernet** [comment]
Will be tricky but I'll see what I can do. It is on my todo list.

**Comment by panthernet** [comment]
Implemented and uploaded on GitHub.  Feel free to leave comments about this feature.
