### ISSUE TITLE
Preliminary Auth can only be done once per character

### ISSUE THREAD

**Issue by Bluedagger21** [panthernet/ThunderED#19]
We had a character use our preliminary auth but we never got around to bringing them into the corp while the token was available (we set ours for a week). When we asked him to go through the process again a week later, it did not add him to the Awaiting Auth section in the HR Module and we could not inspect him.

**Comment by Bluedagger21** [comment]
This may be a little more complicated than originally thought. If the character who did a preliminary auth in the past performs a regular auth after we brought them into the corp, the ESI information passes to the HR Module as a regular member. I guess this more has to do with a character can not be in the Awaiting Auth more than once? No sure... will need to investigate more.

**Comment by panthernet** [comment]
If user has been preliminary authed and then he joins you corp the bot can grant them rights automatically if you setup corps and roles parameters to check. At least it is supposed to work like this :)

Using preliminary AND regular auth for the same task looks excessive.

**Comment by panthernet** [comment]
Haven't founs amy issues with it. Improved messages so you can be correctly notified when a member is authed using AUTO authentication based on preliminary auth data.
