### ISSUE TITLE
ZKillAPI error

### ISSUE THREAD

**Issue by MagnusIIIBR** [panthernet/ThunderED#2]
![image](https://user-images.githubusercontent.com/9530663/39676298-b9620e0c-513e-11e8-81cb-55170b191e65.png)

in debug mode i found 1 problem in this line: 
                    var eText = isAlliance ? "allianceID" : "corpID";
and i changed to:
                    var eText = isAlliance ? "allianceID" : "corporationID";
![image](https://user-images.githubusercontent.com/9530663/39676311-d81ce8da-513e-11e8-943a-842422d31e84.png)
and worked, i make this changes in ZKillAPI.cs

**Comment by panthernet** [comment]
Fixed
