### ISSUE TITLE
Feature Sov index

### ISSUE THREAD

**Issue by Alf-Life** [panthernet/ThunderED#31]
hello, is it possible that the bot ping a loss of military and industrial index has interval defined with the system.

example: system: xxx - military index goes from 5 to 4

**Comment by panthernet** [comment]
Currently there's no way to get the indices as ESI API do not support them. There is a request to CCP to implement it but I doubt it will be done soon. Anyway I'll take another look on this feature if it will be possible to implement it in the future.

**Comment by panthernet** [comment]
Currently, it is possible to trace system Activity Defense Multiplier (ADM) index. No separate index tracing is available though. I will implement tracker for this one.

**Comment by panthernet** [comment]
Implemented in V1.3.2 along with the sov change tracker.
