### ISSUE TITLE
WebAuthModule not assigning group for alliance ID 0

### ISSUE THREAD

**Issue by boredatwork-2011** [panthernet/ThunderED#34]
settings.json has the following but is not assigning "Guest" role:
        "AllowedAlliances": {
          "Guest Alliance": {
            "DiscordRoles": [
              "Guest"
            ],
            "Id": [
              0
            ]

**Comment by panthernet** [comment]
It works. Make sure the role name is correct and that this role (in Discord roles list) is on top of the role which is assigned to Dsicord Bot user.

**Comment by panthernet** [comment]
Fixed error when role were stripping after the assignment
