### ISSUE TITLE
IncursionNotifyModule influence backwards

### ISSUE THREAD

**Issue by paulipa** [panthernet/ThunderED#39]
We just noticed that the influence returned on ESI and the one shown ingame are backwards. ESI is returning 0 % influence for systems that have 100% influence in-game.

I am also assuming that this is causing issues for the boss defeated state:

When a incursion has 100% influence ingame (0% on ESI) the boss status is false making the program think that the boss has been defeated when in fact it has never even spawned yet.

Ingame and bot stats for Mayonhen
(https://i.gyazo.com/6fbee8d7991109b49041d33bc756f890.jpg)

ESI for Mayonhen 
```json
{
    "constellation_id": 20000209,
    "faction_id": 500019,
    "has_boss": false,
    "infested_solar_systems": [
      30001424,
      30001425,
      30001426,
      30001427,
      30001428,
      30001429
    ],
    "influence": 0.45449999094009397,
    "staging_solar_system_id": 30001429,
    "state": "established",
    "type": "Incursion"
  }
```

Since this is the first time i have a look at the incursion endpoint, has the influence always been like that and should it be fixed on the bot? Or has CCP done some sneaky changes once more.

**Comment by panthernet** [comment]
If there is something wrong with ESI query result then you should make an issue at https://github.com/esi/esi-issues/issues

The bot just uses the data supplied by the queries and do not make any calculations. If there is an inconsistency between the data in ESI query and bot discord message then there is definetly something wrong on my side.

**Comment by paulipa** [comment]
Yeah i was just wondering if ESI has always been upside down compared to ingame or not but its more likely that CCP has flipped it at some point. Ill open a ticket for esi and well see what they come up with.
