### ISSUE TITLE
Enhancement: Request to add an auth mode that doesn't expect a new Discord user, but still grab ESI data.

### ISSUE THREAD

**Issue by Bluedagger21** [panthernet/ThunderED#41]
This would mainly be for alts. A person may have 5 accounts, but only one entity is needed to be attached to Discord. We'd still like to do a quick ESI check for simply reviewing.

**Comment by panthernet** [comment]
You can already do it if you set PreliminaryAuth to true and remove all **Allowed** params. The auth will still display command to register code in DIscord but this is not necessary. At this point user token is already saved in DB and available for review. 

I probably will add some new option to avoid following Discord auth page display.

**Comment by panthernet** [comment]
Implemented and will be available in 1.3.0
