### ISSUE TITLE
Auth groups issue

### ISSUE THREAD

**Issue by oskar94** [panthernet/ThunderED#45]
Hello, I'm currently trying to setup the WebAuthModule and ran into a snag.
What i want to do is give users all discord roles they fit into from the auth group. 
eg if a person is in AllowedCharacters to have a special role i still want them to get the roles from being in an alliance/corp that has a entry in AllowedCorporations/Alliances.
Right now it only applies roles from the group they match in the order Corporation>Character>Alliance
Have I missed a option somewhere or is that just not possible at this time?

**Comment by panthernet** [comment]
You can assign a list of roles to a character, corp or alliance like this:
```
	  	"AllowedCharacters":{
			"MyChar":{
				"DiscordRoles": ["Friends", "Allies", "Role2"],
				"Id": [91024152]
			}
		},
```

**Comment by oskar94** [comment]
yes but what i want to do is: 
```json
"AllowedCharacters":{
	"MyChar":{
		"Id": [91024152],
		"DiscordRoles": ["Director"]
	}
},
"AllowedCorporation": {
	"Corp A":{
		"Id":["<corpid a>"],
		"DiscordRoles":["Corp A"]
	},
	"Corp B":{
		"Id":["<corpid b>"],
		"DiscordRoles":["Corp B"]
	}
},
"AllowedAlliance": {
	"My Alliance": {
		"Id": ["<allianceid>"],
		"DiscordRoles": ["Member"]
	}
}
```

So that different corporations can have channels restricted by the corp role while still getting assigned the `Member` role.

**Comment by panthernet** [comment]
Currently it is not possible to assign corp roles through alliance auth. You can solve it by removing alliance auth and grouping all corps by roles Member + Special role1, Member + Special role2 etc.

**Comment by oskar94** [comment]
I was hoping I could avoid that.
However that will introduce another problem, since it gives roles in the order corp>char>ally it will not be possible to have some users have special roles, eg Director/Admin/CEO. 
I have looked at the code and I think a simple fix for that would be to swap the order of checks [here](https://github.com/panthernet/ThunderED/blob/master/ThunderED/API/DiscordAPI.cs#L332) to be char>corp>ally.

**Comment by panthernet** [comment]
I'll check what I can do about the order. You're right that there has to be at least a strict order of auth checks: Character -> Corporation -> Alliance.

**Comment by panthernet** [comment]
Oh wait I misset your pull, will check it! Thanks.

**Comment by panthernet** [comment]
Merged
