### ISSUE TITLE
suggestion : a smarter chat forwarder

### ISSUE THREAD

**Issue by dstevens79** [panthernet/ThunderED#50]
maybe a combination to enable discord mentions - or parse them to mention the proper person based on the authed db entries

now if i get really crazy with the thought train u can have the chat forwarder id eve 
systems 
ship 
corps 
alliance names 
and more im sure - without keywords or symbols infront of them even 

im sure characters can b a difficult load so yea no... but maybe the registered chars in the db?
but surely the first thoughts, and maybe even modules?
that would probably much easier if users have the static eve db on hand to reference maybe? :)

Theres only 64k items in the eve db - but like 60% of them have similar name variant based off some root item name.
you can even have it auto add a contextually smart link to a resource or selection of resources in discord :D

**Comment by panthernet** [comment]
Looks interesting. Chat forwarder is at the back of the list right now due to the very small niche of usage but I will look into it. Thank you.

**Comment by dstevens79** [comment]
I am the oddball as I forward 3 channels and am considering a few more lol

Ty
