### ISSUE TITLE
contract notification enhancements

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#53]
1. basic details only checkbox - if selected the contract notification group only publishes the contracting parties (issued by / issued to)  and the status or status change (issued, completed etc..)

2. direct notification option (if selected for a notification group)
if the creator of the contract publishes his/her discord ID to the in-game contract "description" field the bot sends discord direct messages to that ID , does not publish the notifications in a channel.
This assumes that the ID in question is registered on the same server as the bot.

3. Not sure if it is new or already there: using multiple groups for the same contract e.g. use a normal notification as it is but also add an other notification for the same contract/change with option 2 above. (sending both a direct message and discord channel message for the same contract change by using 2 groups)

**Comment by panthernet** [comment]
This makes sense. Will add it to my TODO list.

**Comment by panthernet** [comment]
http://joxi.ru/Y2L6E7gs7xwyXr

Something like this? Or you prefer to drop embed mode for more condensed view in plain text?
Embeds are able to display URLs, plain text is not

**Comment by srobi** [comment]
404 - page not found

**Comment by panthernet** [comment]
The first field under contract type title is the description field text. I assume that contract can contain description, in this case you can put Discord ID at the end of the text (space delimited) for the suggestion #2.

**Comment by srobi** [comment]
perfect thanks

**Comment by panthernet** [comment]
Implemented in v1.3.8
