### ISSUE TITLE
issue with authentication

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#54]
[extract.txt](https://github.com/panthernet/ThunderED/files/3099993/extract.txt)

Attached extract from auth. All function seems working well except for "Guests" group - the bot provides the auth code but after using it in the channel it does not assign the role (but change the ticker, name and gives an auth message ("successfully authenticated."). It is a separate button.  (char  and alliance ID replaced in the file)

**Comment by panthernet** [comment]
Fixed in 1.3.8
