### ISSUE TITLE
Contract notification - Bot answering to keywords

### ISSUE THREAD

**Issue by dreej-net** [panthernet/ThunderED#55]
Hi,

Got several ideas that could be usefull :

**- Filter options of displayed notifications**
Would it be possible to filter contracts' informations out ?

**- Bot responses to keywords**
A user types in chat :
@Bot [keyword] [contract_identifier]

Where :
Bot = Bot name.
keyword = Desired information (most common would be "status")
contract_identifier = To target a specific contract (issuer name ? issuer id ? issued date as kind of a code : [ddmmyyyy-hhmm] ?)

And Bot answers with the same notification "template" when there will be one if ever, but only with desired information + extra "default" info depending on Admin choices.
There would be therefore 2 kind of Templates :
- The "automatic" ones, that are triggered with notifications.
- The "response" ones, that are triggered on chat read.

**Comment by panthernet** [comment]
Please clarify information about filters. What exact filtering do you need?

**Comment by dreej-net** [comment]
For each and every json variables ?  

`
            public long acceptor_id;
            public long assignee_id;
            public string availability;//"public", "personal"
            public double buyout;
            public double collateral;
            public long contract_id;
            public string date_accepted;
            public string date_completed;
            public string date_expired;
            public string date_issued;
            public int days_to_complete;
            public long end_location_id;
            public bool for_corporation;
            public long issuer_corporation_id;
            public long issuer_id;
            public double price;
            public double reward;
            public long start_location_id;
            public string status;//"outstanding","finished"
            public string title;//desc
            public string type;// "item_exchange",courier
            public double volume;

            [JsonIgnore]
            public DateTime? DateExpired => string.IsNullOrEmpty(date_expired) ? null : (DateTime?)DateTime.Parse(date_expired).ToUniversalTime();
            [JsonIgnore]
            public DateTime? DateIssued => string.IsNullOrEmpty(date_issued) ? null : (DateTime?)DateTime.Parse(date_issued).ToUniversalTime();
            [JsonIgnore]
            public DateTime? DateCompleted => string.IsNullOrEmpty(date_completed) ? null : (DateTime?)DateTime.Parse(date_completed).ToUniversalTime();
            [JsonIgnore]
            public DateTime? DateAccepted => string.IsNullOrEmpty(date_accepted) ? null : (DateTime?)DateTime.Parse(date_accepted).ToUniversalTime();`
