### ISSUE TITLE
Radius Killfeed

### ISSUE THREAD

**Issue by Alf-Life** [panthernet/ThunderED#56]
Is it possible to exclude the kills made by the alliance put in the livekillfeed?

**Comment by panthernet** [comment]
Do you mean you want kills displayed in Radius to be excluded from LiveKillFeed ?

**Comment by Alf-Life** [comment]
nope inverse alliance kill feed by livekill be exclude of radius kill feed

**Comment by panthernet** [comment]
I see, will look into it.

**Comment by panthernet** [comment]
Implemented in v1.3.8
