### ISSUE TITLE
Killmail template improvements request

### ISSUE THREAD

**Issue by oskar94** [panthernet/ThunderED#59]
I have been working on customizing the killmail templates for my server and have run into some things that I would like to do but is currently not possible. 

- Setting the timestamp of the embed to the killmail loss time instead of current time since there is almost always a delay between a kill happening and it getting posted on zkill.
- `{victimAllyOrCorpName}`, `{attackerAllyOrCorpName}` To be able to display either alliance name or if they are not in an alliance the corp name.
- `{systemRegion}`  To also show what region the system is in to give better location context. 
- `{isSoloKill}` Should be self explanatory.

**Comment by panthernet** [comment]
Okay, I will look into it.

**Comment by panthernet** [comment]
Implemented in v1.3.10.
Added: **{victimAllyOrCorpName}, {victimAllyOrCorpTicker}, {attackerAllyOrCorpName}, {attackerAllyOrCorpTicker}, {constName}, {regionName}, {isSoloKill}, {isAwoxKill}, {iskFittedValue}**
