### ISSUE TITLE
Installing?

### ISSUE THREAD

**Issue by gbrann** [panthernet/ThunderED#6]
Ok, I'm wanting to test this locally first.. simple. I am using the Windows 10 executable that is premade, I download it and do the settings json, but when I open the ThunderED.exe it just gives me a blank window. Nothing. No Discord pings no bots, nothing. Maybe I'm missing the obvious, but umm.. am I missing something?

**Comment by panthernet** [comment]
Hmm, never happened to me before. First of all, download the latest 1.1.2 version and then try to run it as Administrator. May be there are some OS level restrictions. Also check if there are any log files in the **logs** folder.

**Comment by smoorc0** [comment]
Also make sure you configure the settings file

**Comment by panthernet** [comment]
Wow, I've encountered this issue myself recently and I'm sure this is not the app problem. Possibly some glitch in .NET Core framework. It happened only once and simple restart has solved it. Haven't found anything similar on the internet resources yet.

**Comment by gbrann** [comment]
I'm installing 1.1.2 now, I'll update you on how it goes.

**Comment by gbrann** [comment]
ok. I downloaded the 1.1.3, verified the settings.def.json was complete. Still the same issue. I tried admin mode and rebooted. Blank window. No bot shows up in discord. Question - where do I find the logs?

**Comment by gbrann** [comment]
I'm pretty sure the issue is a BK&C issue, but yeah.. this is fubar. lol

**Comment by gbrann** [comment]
I'm going to try a different box, see if the issue is isolated to my machine

**Comment by gbrann** [comment]
Tried two different boxes, a fresh install on Win7, and an Azure Cloud Win10. Nothing will run. I either get a blank box that never goes away or blank box that opens then shuts down in seconds. I'm on the latest build. Idk what the hell is going on here. Here's my settings:

`{
  "config": {
    "botDiscordToken": "NDQ**********n1FaO0yLDtS-MA",
    "botDiscordName": "NEI-BOT",
    "botDiscordGame": "with Shey's heart.",
    "botDiscordCommandPrefix": "&",
    "discordGuildId": 32328****946,
    "discordAdminRoles": [ "Bot" ],
	  "discordGeneralChannel": 38*****925462531,
	  "comForbiddenChannels": [],
	  "language": "en-US",
	  "useEnglishESIOnly": "true",

    "moduleWebServer": true,
    "moduleAuthCheck": false,
    "moduleAuthWeb": false,
    "moduleCharCorp": true,
	"moduleReliableKillFeed": true,
    "moduleLiveKillFeed": false,
    "moduleRadiusKillFeed": false,
    "modulePriceCheck": true,
    "moduleTime": true,
    "moduleFleetup": true,
    "moduleJabber": false,
    "moduleMOTD": false,
    "moduleNotificationFeed": true,
    "moduleStats": true,
    "moduleTimers": true,
    "moduleMail": true,
    "moduleIRC": false,
    "moduleTelegram": false,
    "moduleChatRelay": true,
    "moduleIncursionNotify": false,

    "zkillLiveFeedRedisqID": "",
    "timeFormat": "dd.MM.yyyy HH:mm:ss",
    "shortTimeFormat": "dd.MM.yyyy HH:mm",
    "welcomeMessage": true,
    "cachePurgeInterval": 30,
    "memoryUsageLimitMb": 100,
    "logSeverity": "Info",	
    "logNewNotifications": true,
    "databaseProvider":  "sqlite",
    "databaseFile": "edb.db",
    "requestRetries": 3
  },

  "mailModule": {
    "checkIntervalInMinutes": 2,
    "authGroups":{
      "Exodus": {
        "id": 190*****77,
        "labels": [ "exodus" ],
        "senders": [],
        "includePrivateMail":  false, 
        "channel": 4472******84291,
      },
	  "Buyback": {
        "id": 19****77,
        "labels": [ "buyback" ],
        "senders": [],
        "includePrivateMail":  false, 
        "channel": 4472******369,
      },
    }
  },

  "webServerModule": {
    "webListenIP": "IP",
    "webListenPort": 80,
    "webExternalIP": "IP",
    "webExternalPort": 80,
    "discordUrl": "https://discord.gg/FJ******",
    "ccpAppClientId": "22b1523e**********f2f9703",
    "ccpAppSecret": "lVcnNx**************7PLsEtV8zScfLz",
  },
  
  "timersModule": {
    "authTimeoutInMinutes": 10,
    "autoAddTimerForReinforceNotifications": true,
    "grantEditRolesToDiscordAdmins": true,
    "announces": [60, 10],
    "announceChannel": 3456********321,
    "accessList": {
      "NEIN":{
        "isAlliance": true,
        "isCharacter": false,
        "id": 9****84,
      }
    },	 
	  
    "editList": {
      "NEIN":{
        "isAlliance": true,
        "isCharacter": false,
        "id": 9*****84,
      }
    }
  },

  "radiusKillFeedModule": {
    "enableCache": false,
    "groupsConfig": {
      "group1": {
        "radius": 4,
        "radiusChannel": 402*******0852381,
        "radiusSystemId": 3*****8***18,
        "minimumValue": 0
      }
    }
  },

  "statsModule": {
    "autoDailyStatsChannel": 381459112******2531,
    "autoDailyStatsDefaultCorp": 98***784,
    "autodailyStatsDefaultAlliance": 0
  },
    
    "reliableKillFeed": {
    "queryIntervalInSeconds": 30,
    "groupsConfig": {
      "groupName": {
        "losses": true,
        "//": "Post all group kills to separate chat channel",
        "discordChannel": 4025******0852381,
        "corpID": 98****,
        "allianceID": 0,
        "minimumValue": 0,
        "minimumLossValue": 0,
        "bigKillValue": 20000000000,
        "//": "Post BIG kills to separate chat channel",
        "bigKillChannel": 0,		
        "bigKillSendToGeneralToo": true
      }
    }
  },
  
  "liveKillFeed": {
    "enableCache": false,
    "bigKill": 10000000000,
    "//": "Post GLOBAL BIG kills to separate chat channel",
    "bigKillChannel": 0,
    "losses": true,
    "groupsConfig": {
      "groupName": {
        "//": "Post all group kills to separate chat channel",
        "discordChannel": 0,
        "corpID": 0,
        "allianceID": 0,
        "minimumValue": 0,
        "minimumLossValue": 0,
        "bigKillValue": 300000000,
        "//": "Post BIG kills to general chat channel",
        "bigKillChannel": 0,		
        "bigKillSendToGeneralToo": true
      }
    }
  },
  
  "WebAuthModule": {
    "authCheckIntervalMinutes": "480",
    "discordUrl": "https://discord.gg/FJ2****",
    "ccpAppClientId": "22b1523e*******28d20421f2f9703",
    "ccpAppSecret": "lVcnNx9Y7F******XO4Z8x57PLsEtV8zScfLz",
    "exemptDiscordRoles": [ "Executive", "Guest", "Attache'", "Blue", ],
    "authReportChannel": 0,
	  "//": "Channels where !auth command is allowed. Empty - everywhere",
	  "comAuthChannels":  [],
    "enforceCorpTickers": true,
    "enforceCharName": true,
    "authGroups": {
      "group1": {
        "corpID": 98****784,
        "allianceID": 0,
        "memberRole": ""
      }
    }
  },
  "resources": {
    "imgCitLowPower": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitLowPower.png",
    "imgCitUnderAttack": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitUnderAttack.png",
    "imgCitAnchoring": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitAnchoring.png",
    "imgCitDestroyed": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitDestroyed.png",
    "imgCitLostShield": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitLostShield.png",
    "imgCitLostArmor": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitLostArmor.png",
    "imgCitOnline": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitOnline.png",
    "imgCitFuelAlert": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitFuelAlert.png",
    "imgCitServicesOffline": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgCitServicesOffline.png",
    "imgLowFWStand": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgLowFWStand.png",
    "imgMoonComplete": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgMoonComplete.png",
    "imgWarAssist": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgWarAssist.png",
    "imgWarDeclared": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgWarDeclared.png",
    "imgWarInvalidate": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgWarInvalidate.png",
    "imgWarSurrender": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgWarSurrender.png",
    "imgTimerAlert": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgTimerAlert.png",
    "imgMail": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgMail.png",
    "imgIncursion": "https://raw.githubusercontent.com/panthernet/ThunderED/master/ThunderED/Content/Icons/imgIncursion.png",
  },

  "notificationFeedModule": {
    "checkIntervalInMinutes": 2,
    "groups": {
      "groupName1": {
        "characterID": 1904****7,
        "defaultDiscordChannelID": 38145******925462531,
        "filters": {
          "filter1": {		  
            "notifications": [
              "StructureUnderAttack", 
              "StructureWentLowPower", 
              "StructureWentHighPower", 
              "StructureLostArmor", 
              "StructureLostShields", 
              "StructureFuelAlert", 
              "StructureOnline", 
              "StructureAnchoring", 
              "StructureDestroyed",
              "OrbitalAttacked",
              "AllAnchoringMsg",
              "AllWarDeclaredMsg", 
              "AllWarInvalidatedMsg", 
              "AllyJoinedWarAggressorMsg", 
              "AllyJoinedWarAllyMsg", 
              "AllyJoinedWarDefenderMsg", 
              "AllWarRetractedMsg", 
              "AllWarSurrenderMsg", 
              "CorpWarRetractedMsg", 
              "CorpWarDeclaredMsg", 
              "AcceptedSurrender",
              "CharLeftCorpMsg", 
              "CharAppAcceptMsg", 
              "SovAllClaimAquiredMsg",
              "SovAllClaimLostMsg",
              "SovereigntyIHDamageMsg",
              "SovereigntySBUDamageMsg",
              "SovereigntyTCUDamageMsg",
              "StationConquerMsg",
              "SovStructureDestroyed",
              "SovStationEnteredFreeport",
              "SovCommandNodeEventStarted",
              "SovStructureReinforced",
              "StationServiceDisabled",
              "EntosisCaptureStarted",
              "MoonminingExtractionFinished", 
              "MoonminingLaserFired", 
              "FWAllianceWarningMsg", 
            ],
            "channelID": 381459*******31,
            "charMentions": [@here],
            "roleMentions": []
          },
        },		
      }
    }
  },

  "filters": {
    "StructureUnderAttack": 0,
    "AllWarDeclaredMsg": 0,
    "FWAllianceWarningMsg": 0,
    "StructureWentLowPower": 0,
    "StructureWentHighPower": 0,
    "StructureLostArmor": 0,
    "StructureLostShields": 0,
    "MoonminingExtractionFinished": 0,
    "StructureFuelAlert": 0,
    "MoonminingLaserFired": 0,
    "AllWarInvalidatedMsg": 0,
    "StructureDestroyed": 0,
    "StructureOnline": 0,
    "CharLeftCorpMsg": 0,
    "CharAppAcceptMsg": 0,
    "SovStructureDestroyed": 0,
    "SovStationEnteredFreeport": 0,
    "SovCommandNodeEventStarted": 0,
    "SovStructureReinforced": 0,
    "StationServiceDisabled": 0,
    "CorpWarDeclaredMsg": 0,
    "CorpWarInvalidatedMsg": 0,
    "EntosisCaptureStarted": 0,
    "StructureAnchoring": 0,
    "AllyJoinedWarAggressorMsg": 0,
    "AllyJoinedWarAllyMsg": 0,
    "AllyJoinedWarDefenderMsg": 0,
	  
    "AcceptedSurrender": 0,
    "AllAnchoringMsg": 0,
    "AllWarRetractedMsg": 0,
    "AllWarSurrenderMsg": 0,
    "CorpWarRetractedMsg": 0,
    "SovAllClaimAquiredMsg": 0,
    "SovAllClaimLostMsg": 0,
    "SovereigntyIHDamageMsg": 0,
    "SovereigntySBUDamageMsg": 0,
    "SovereigntyTCUDamageMsg": 0,
    "StationConquerMsg": 0,
  }
},

  "motd": {
    "motdkeyID": "",
    "motdvCode": "",
    "motdcharid": "",
    "motdtopicchan": 0,
    "topicInterval": "30",
    "MOTDChan": "",
    "updatetopic": false,
    "restricted": 0
  },

  "fleetupModule": {
    "UserId": "7******",
    "APICode": "ZcxeT7FP*********0wYxjtW6YZWI",
    "AppKey": "l4rBQgLc*******Uw1sxRuOX2Ah",
    "GroupID": "4******",
    "channel": 3456*******2321,
    "announce_post": true,
    "announce": [ 5, 60 ]
  },

  "jabberModule": {
    "domain": "example.com",
    "username": "username",
    "password": "password",
    "filter": false,
    "debug": false,
    "defchan": 0,
    "filters": {
      "SUPER": 0,
      "BLOPS": 0
    },
    "prepend": "@here"
  },

  "ircModule": {
    "Server": "chat.freenode.net",
    "Port": 6667,
    "UseSSL": false,
    "Password": null,
    "Nickname": "DefaultUser-TH",
    "Nickname2": null,
    "Username": "DefaultUser-TH",
    "Realname": "realname",
    "Invisible": true,
    "AutoReconnect": true,
    "AutoReconnectDelay": 5000,
    "AutoRejoinOnKick": false,
    "QuitReason": "Leaving",
    "SuppressMOTD": true,
    "SuppressPing": false,
    "ConnectCommands": [],
    "RelayChannels": [
      {
        "irc": "#mychannel",
        "discord": 0,
        "discordFilters": [ "!auth", "/join" ],
        "discordFiltersStartsWith": [ "!" ],
        "ircFilters": [],
        "ircFiltersStartsWith": [ "/" ],
        "relayFromDiscordBotOnly": false,
        "ircUsers": [],
      },
    ],
    "AutoJoinWaitIdentify": false,
    "AutoResponse": false,
    "AutoResponseList": [],
    "AutoResponseDelay": 10000
  },

  "telegramModule": {
    "token": "YOUR TOKEN",
    "RelayChannels": [
      {
        "telegram": 0,
        "discord": 0,
        "discordFilters": [ "!auth", "/join" ],
        "discordFiltersStartsWith": [ "!" ],
        "telegramFilters": [],
        "telegramFiltersStartsWith": [ "/" ],
        "relayFromDiscordBotOnly": false,
        "telegramUsers": [],
      }
    ],
  },

  "chatRelayModule": {
    "RelayChannels": [
      {
        "eveChannelName": "OPPPS Intel",
        "discordChannelId": 3603999*******333642,
        "code": "UWISH",
      }
    ]
  },

  "incursionNotificationModule": {
	  "DiscordChannelId": 0,
	  "Regions": [],
	  "Constellations": [],
	  "ReportIncursionStatusAfterDT": true,
  }
}`

**Comment by gbrann** [comment]
ok! now I'm getting this..

https://imgur.com/a/xpmgczl

**Comment by smoorc0** [comment]
try creating a new settings.json from scratch using settings.def.json

**Comment by gbrann** [comment]
Did that, no change. I get the results as shown in that image.
