### ISSUE TITLE
working on this all day

### ISSUE THREAD

**Issue by deadpoolex** [panthernet/ThunderED#60]
ive been working on this all day and still confused/cant figure out how to start the bot or add the ccp website stuff... a video tut may help if possible but im lost

**Comment by dreej-net** [comment]
Have you followed wiki instructions ?
https://github.com/panthernet/ThunderED/wiki/Build-&-Installation

**Comment by deadpoolex** [comment]
i followed the instructions but i still dont understand how to start the bot/ how to setup the authentication to allow people only from my alliance into the discord. i may just be doing something wrong

**Comment by panthernet** [comment]
If you have any specific questions feel free to ask them on Discord
