### ISSUE TITLE
Issue - Multiple contracts saved in Data Base with same ID

### ISSUE THREAD

**Issue by dreej-net** [panthernet/ThunderED#62]
Multiple contacts saved in Data Base with same ID.

My set-up is as followed :
- 2 different filters in a single group.
- Filter 1 : Full detailed notif in Channel #123
- Filter 2 : Limited detailed notif in Channel #456

Contracts are gotten by 1 single character with Corporation feeds only, this character ID only is in settings.json.
Corporation has 3 members total managing (accepting / rejecting / completing) contracts.

https://imgur.com/uVSVAvx

**Comment by dreej-net** [comment]
I'm using "unofficial" latest version, still doing the same thing :
https://imgur.com/E9FvN6o

Before publishing and launching new unofficial version, i've "cleaned" data base by erasing duplicated entries with same ID so that only 1 remains.

**Comment by dreej-net** [comment]
After a few days observing, i can tell that it's semi-solved.

In limited details channel, everyhting goes fine.
But in full details channel, i still get multiple notifications.

Analysing console, a contract, that has already been notified as "outstanding" is notified twice in full detail channel when it changes status 

first console capture shows 2x2 notifications "Contract XXX is accepted" -> ok 
But, there's a "New contract found" notification right after, and when i check in earlier timestamps, this contract ID has already been found :

1
https://imgur.com/i54gOy2
2
https://imgur.com/6T0AdPF

**Comment by panthernet** [comment]
I assume this is due to the nature of the filters. They are implemented to be processed once for every contract. Do you need a separate channel for new contracts and separate channel for status changes?

Send me your Contracts config section (you can ommit IDs) so I can get a hold on a problem.

**Comment by dreej-net** [comment]
My contracts settings are in the 3rd image linked

https://imgur.com/vtmZMwG

**Comment by panthernet** [comment]
@dreej-net do you still experience this issue?

**Comment by panthernet** [comment]
Hopefully fixed in V1.3.13. Implemented some fixes and checked on an empty database. 

You can edit DB and set all fields in `contracts` table to `[]` value - empty data. It should update itself with all ongoing contracts on the first check.
