### ISSUE TITLE
RadiusKill report kills 2 times

### ISSUE THREAD

**Issue by erikterr** [panthernet/ThunderED#65]
As per object our radius kill report every kill 2 times, pods/ships. http://prntscr.com/nl933b for example

**Comment by panthernet** [comment]
Will take a look.

**Comment by panthernet** [comment]
Can't reproduce. May be you set up several feed groups which are overlapping? Or do you have live kill feed also enabled in this channel?

You can try setting `AvoidDupesAcrossAllFeeds` to `true`

**Comment by panthernet** [comment]
@erikterr make sure all group names in KM feed module settings are unique. Also I've made some improvements in V1.3.15 so `AvoidDupesAcrossAllFeeds` should work correctly.
