### ISSUE TITLE
Add Groups to User via Command

### ISSUE THREAD

**Issue by kanelarrete** [panthernet/ThunderED#67]
Hello!

Just recently started to use this and really like it. One enhancement that I think would be really useful would be the ability to have users add groups (that they have available to them) themselves. These roles could be setup via the ThunderED config and only those roles would available to this command. 

Commands:
!join Groupname (This command joins the group)
!leave Groupname (This leaves the group)
!listgroups (This lists all groups available to this user)

The Idea behind this is that there can be optional roles available to users that admins do not need to manage joins / leaves.

The caveat to this would be the users should have to pass a specific permission state (can be controlled via discord roles they are in as it would be inherited from the Discord Auth module). Want to make sure that someone who should not have access to an area can gain it via this method.  

Hopefully this makes sense. 

Thanks!

**Comment by panthernet** [comment]
Implemented in V1.3.13
Read version.txt for details
