### ISSUE TITLE
Notification Message Customization

### ISSUE THREAD

**Issue by smoorc0** [panthernet/ThunderED#7]
Thing I would like to see the most is being able to customize who is mentioned.

Could be further extended to make the whole message customizable however this isn't needed.

**Comment by panthernet** [comment]
Accepted. Will look into it.

**Comment by panthernet** [comment]
Implemented in https://github.com/panthernet/ThunderED/commit/e0e99cb4e263332eb0138b8d02a5cadfadda3136
