### ISSUE TITLE
three groups in notifications

### ISSUE THREAD

**Issue by Vortex28** [panthernet/ThunderED#70]
https://pastebin.com/R0kFbtmp
trying to create three groups with different notification filters for three different channels
first group filter looking good and giving some text to discord channel, next group completely ignores types of notifications
ESI giving this type: "type": "StructureUnderAttack"

**Comment by panthernet** [comment]
I will check the issue but you still do it wrong. Don't create many groups for ONE character, use filters instead. You can set `ChannelID` inside filter to redirect feed to that channel.

**Comment by panthernet** [comment]
I will check the issue but you still do it wrong. Don't create many groups for ONE character, use filters instead. You can set `ChannelID` inside filter to redirect feed to that channel.

**Comment by panthernet** [comment]
@Vortex28 Yes, currently you can't have one character in several groups. Use filters within one group instead.

**Comment by panthernet** [comment]
Should be fixed in V1.4.0
