### ISSUE TITLE
Radius Modification

### ISSUE THREAD

**Issue by Harakiri42** [panthernet/ThunderED#72]
Can the Radius Killmail feature be modified so for example it can be set that only specific Ship Class / Ship x, y, z and alliance a,b,c can be excluded from the pull and given a range for that?

Like

Only Pull Class "Strategic Cruiser", Ship "Hel" and Class "Titan" for Jita but exclude Corp "The Scope" or
Only Pull Carrier, Naglfar and Drake while 7 AU range of Jita or character xyz but exclude Alliance "123"

i guess the Corp and Alliance can be handled over the zkill ID?

**Comment by panthernet** [comment]
Can be modified. Will take a look when I'll have some free time.

**Comment by panthernet** [comment]
Implemented in V1.3.15. Class can't be specified so you have to list all the required ship types in a filter. Hopefully by their names.
