### ISSUE TITLE
Automated dockerhub build

### ISSUE THREAD

**Issue by mckernanin** [panthernet/ThunderED#78]
Hey there! After fighting with SEAT's discord auth for a bit, I found this and it's fantastic. Would you mind setting up automated builds on releases with dockerhub? That way people can pull an image vs. building locally, and also be able to use it on something like kubernetes. Thanks!

**Comment by panthernet** [comment]
Hi, never tried it. Some guides will be nice, thanks.

**Comment by mckernanin** [comment]
https://docs.docker.com/docker-hub/builds/

Essentially a super simple CI pipeline, free from docker. Would make images available like this:
https://hub.docker.com/r/mckernanin/thunderd/tags

So that instead of building on their servers, people can just pull the image and run it with something like `docker run panthernet/thundered:1.3.8`

**Comment by panthernet** [comment]
https://hub.docker.com/r/panthernet/thundered

Check if it works please.
