### ISSUE TITLE
monitoring /uptime robot

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#81]
1. define a new port on webserver for monitoring only
2. allow a simple username/pwd auth on the port (to an empty webpage)
3. DeclineIfNotConnected parameter: if the bot is not connected to discord then decline auth on the monitoring port

This would allow a multi layer monitoring of the bot with uptime robot (https://uptimerobot.com/)

**Comment by panthernet** [comment]
Implemented in V1.4.1
Auth is not needed here, any request to the specified port will return one of the following values: OK, NO_ESI, NO_CONNECTION, NO_DISCORD

Query throttling is implemented so any excessive usage will be eiminated.
