### ISSUE TITLE
Kubernetes Friendly Logging

### ISSUE THREAD

**Issue by mckernanin** [panthernet/ThunderED#84]
With the current file logging options, I'm running a container for each log that tails the log into STDOUT on containers, and it's kind of silly. There are a few ways this could be better. 

1. Offer a combined log file, where everything wrote out to 1 log file. This is a decent option, but still requires additional setup past what would typically be required to run a container in kubernetes.

2. Offer a mode where logs would be written to STDOUT.

Option 2 would be much preferred, Option 1 would be an improvement over current functionality.

**Comment by panthernet** [comment]
According to docs `Console.WriteLine` method already writes output to `standard output stream`. Not sure how I can handle this on Linux. Need more research.

**Comment by panthernet** [comment]
I can use `Console.SetOut()` method to redirect console to new output. Do you think we can specify some special output under Linux for correct redirection?

**Comment by panthernet** [comment]
Implemented option number 1 in V1.4.1.
Note that `notifications_lg.log`  still writes separately as it has distinct purpose
