### ISSUE TITLE
Move docs from github wiki?

### ISSUE THREAD

**Issue by mckernanin** [panthernet/ThunderED#85]
It'd be nice to be able to PR updates to the docs, which isn't possible with github wikis. There are lots of great tools out there for this, like [Docusaurus](https://docusaurus.io/).

I'd be happy to contribute moving the docs over to something like this, just let me know if you have any preferences.

**Comment by panthernet** [comment]
This tool is great but I prefer something cloud based so I don't have to host it myself. I had cases in the past when self hosted docs for older projects has been casted down into oblivion. 

If there're any cloud solutions for this ithey can be worth nvestigating. Or you can use Git to clone existing WIKI repo https://github.com/panthernet/ThunderED.wiki.git  and probably push updates.  Haven't tried to use it before, not sure how it works.
