### ISSUE TITLE
User can not auth and receive roles

### ISSUE THREAD

**Issue by iamschleep** [panthernet/ThunderED#91]
User was guest role on the discord for a bit, but now when he tries to auth while being in the corporation to receive roles the bot gives this error:
Unable to accept user as he don't fit into auth group access criteria!

**Comment by panthernet** [comment]
There're some issues with auth in the latest version. Working on the fix.

**Comment by iamschleep** [comment]
Appreciate it :)

**Comment by panthernet** [comment]
@iamschleep Update to the recent src version from GitHub or wait for the release version. This issue should be solved. Hopefully.
