### ISSUE TITLE
notification parsing issue with cyrilic

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#97]
name and IDs are altered
**notification.lg:**
CorpAppNewMsg [1071408599]
applicationText: "\u042F \u043C\u0430\u0439\u043D\u0435\u0440 \u0445\u043E\u0447\u0443
  \u043C\u0430\u0439\u043D\u0438\u0442\u044C"
charID: 2115483999
corpID: 755437999

**copy from ingame:**
New application from Zzzz Dddd
From: Zzzz Dddd
Sent: 2019.07.19 20:02

Я майнер хочу майнить

**Comment by panthernet** [comment]
should be fixed in release
