### ISSUE TITLE
contract notification - completed status not published

### ISSUE THREAD

**Issue by srobi** [panthernet/ThunderED#98]
contract notification - completed status not published  since v1.4 I think

also, it maybe connected, repeated log entry: 
07/23/2019 12:03:12 [Critical]: Contracts 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ThunderED.Modules.ContractNotificationsModule.ProcessContracts(Boolean isCorp, ContractNotifyGroup group, Int64 characterID, String token) in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Modules\ContractNotificationsModule.cs:line 206
   at ThunderED.Modules.ContractNotificationsModule.Run(Object prm) in D:\Projects\EVE\ThunderED\ThunderED_git\ThunderED\Modules\ContractNotificationsModule.cs:line 162

**Comment by srobi** [comment]
resolved

**Comment by srobi** [comment]
still not getting completed courier contract notifications
no error in log

**Comment by panthernet** [comment]
Can you get me the sepcified contract data directly from ESI? https://esi.evetech.net/ui/#/Contracts
You have to auth there pressing the lock icon and select contracts permissions.

I need a message body for the contract ypu miss the completion event for.

**Comment by srobi** [comment]
```{
    "acceptor_id": 95823213,
    "assignee_id": 98457033,
    "availability": "personal",
    "collateral": 0,
    "contract_id": 148473265,
    "date_accepted": "2019-08-12T09:33:43Z",
    "date_completed": "2019-08-12T09:38:36Z",
    "date_expired": "2019-08-26T09:29:33Z",
    "date_issued": "2019-08-12T09:29:33Z",
    "days_to_complete": 6,
    "end_location_id": 1030797516386,
    "for_corporation": false,
    "issuer_corporation_id": 98457033,
    "issuer_id": 2113468992,
    "price": 0,
    "reward": 0,
    "start_location_id": 1021700307171,
    "status": "finished",
    "title": "",
    "type": "courier",
    "volume": 2
  },```

sample contract; I got notification as outstanding and in progress status but never completed

**Comment by panthernet** [comment]
And contract notif settings please

**Comment by srobi** [comment]
"ContractNotificationsModule": {
    "CheckIntervalInMinutes": 5,
    "MaxTrackingCount": 150,
    "Groups": {
      "jfcourier": {
        "CharacterIDs": [
          95814771
        ],
        "Filters": {
          "normal": {
            "Availability": [
              "corporation"
            ],
            "Types": [
              "courier"
            ],
            "Statuses": [
              "finished_issuer",
              "finished",
              "cancelled",
              "rejected",
              "failed",
              "deleted",
              "reversed",
              "in_progress",
              "outstanding",
              "finished_contractor"
            ],
            "DiscordChannelId": 579286154164043786,
            "FeedIssuedBy": false,
            "FeedIssuedTo": true,
            "ShowIngameOpen": false,
            "ShowOnlyBasicDetails": false,
            "RedirectByIdInDescription": true,
            "PostToChannelIfRedirected": false
          }
        },
        "FeedPersonalContracts": true,
        "FeedCorporateContracts": true,
        "ButtonText": "JF Auth",
        "StopOnFirstFilterMatch": false,
        "DefaultMention": ""
      }
    }
  },

**Comment by srobi** [comment]
as a comment did additional test and seems that the completed published IF there is something in the description field

"RedirectByIdInDescription": true,
"PostToChannelIfRedirected": false
 functions maybe the rootcause

**Comment by panthernet** [comment]
Tested with empty title and it works for me :|  It was issued to character or corporation? Can you describe the settings? Contracts ESI is pretty messed up and aunable to provide clear data...

**Comment by srobi** [comment]
issued to a corporation, accepted/completed by one member of the corp. courier contracts.

```
 {
    "acceptor_id": 95823213,
    "assignee_id": 98457033,
    "availability": "personal",
    "collateral": 0,
    "contract_id": 148529207,
    "date_accepted": "2019-08-14T11:19:34Z",
    "date_completed": "2019-08-14T11:23:19Z",
    "date_expired": "2019-08-28T11:19:17Z",
    "date_issued": "2019-08-14T11:19:17Z",
    "days_to_complete": 6,
    "end_location_id": 1021700307171,
    "for_corporation": false,
    "issuer_corporation_id": 98457033,
    "issuer_id": 2113468992,
    "price": 0,
    "reward": 0,
    "start_location_id": 1030797516386,
    "status": "finished",
    "title": "test99",
    "type": "courier",
    "volume": 2
  }
```

this contract has very similar details as the prior example, but this generated completed message

**Comment by srobi** [comment]
deleted all contract related DB entry and re-created the same setting and it works now - it got broken at some point at upgrade from 1.4.0 to higher versions.
I cannot recreate the problem, closing the ticket.
